[project]
name = "djangobot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "django>=5.2",
    "requests>=2.32.3",
]
